#  Pr no 3

class_a = int(32)
class_b = int(45)
class_c = int(51)
class_a_first = (int(class_a)//5)
class_b_first = (int(class_b)//7)
class_c_first = (int(class_c)//6)
print("Number of each group:")
print("first class 1 :" + str(class_a_first))
print("first class 2 :" + str(class_b_first))
print("first class 3 :" + str(class_c_first))
print("Number of leftover student:")
class_a_second = (int(class_a)%5)
class_b_second = (int(class_b)%7)
class_c_second = (int(class_c)%6)
print("second class 1 :" + str(class_a_second))
print("second class 2 :" + str(class_b_second))
print("second class 3 :" + str(class_c_second))